# Session 3 | 2. Loading and Exploring Data <a class="anchor" id="top"></a>

> Author: Patrícia Loureiro Rodrigues <plrodrigues@pbs.up.pt>
>
> Publication Date: April 2026

## Table of contents:
1. [What is Pandas?](#pandas)
2. [Loading a CSV File](#csv)
3. [Loading the Project Data from MySQL](#gas)
4. [Inspecting the Data](#inspect)
5. [Parsing Timestamps](#timestamps)
6. [Loading a Second Table: Companies](#position)
7. [Handling Missing Values](#nulls)

---

At the end of this notebook, you will be able to:

- Load a CSV file into a Pandas DataFrame using `pd.read_csv()`
- Connect to a MySQL database and load project data using `pd.read_sql()`
- Inspect the structure and content of a dataset
- Parse a Unix millisecond timestamp column into proper datetime objects
- Identify missing values and understand their implications for analysis
- Understand the multi-table structure of the LinkedIn job postings dataset

---

## 🐼 What is Pandas? <a class="anchor" id="pandas"></a>

**Pandas** is the standard Python library for working with structured (tabular) data. Think of it as a programmable spreadsheet.

- Built on top of NumPy
- Works with **DataFrames** (tables) and **Series** (single columns)
- Handles real-world messy data: missing values, mixed types, timestamps
- Essential for any data analysis or BI workflow

Our dataset: **LinkedIn Job Postings (2023–2024)** — 40,059 real job postings scraped from LinkedIn, covering salaries, locations, experience levels, remote work, and company data across 11 related tables.

---

## 📂 Loading a CSV File <a class="anchor" id="csv"></a>

### 🧩 1. `pd.read_csv()`

The most common way to load data into Pandas is from a **CSV** (comma-separated values) file. `pd.read_csv()` reads the file and returns a DataFrame.

```python
df = pd.read_csv("../data/sample.csv")
```

Let's try it with one of the mapping files from our dataset — a small, clean table with industry codes and names.

In [1]:
import pandas as pd

# Load a local CSV file — industries mapping table
df_industries = pd.read_csv("../data/LinkedIn Job Postings (2023 - 2024)/mappings/industries.csv")

# First look at the data
df_industries.head()

   industry_id                         industry_name
0            1       Defense and Space Manufacturing
1            3       Computer Hardware Manufacturing
2            4                  Software Development
3            5          Computer Networking Products
4            6  Technology, Information and Internet

In [4]:
df_industries.head()

   industry_id                         industry_name
0            1       Defense and Space Manufacturing
1            3       Computer Hardware Manufacturing
2            4                  Software Development
3            5          Computer Networking Products
4            6  Technology, Information and Internet

In [5]:
df_industries.shape

(422, 2)

In [6]:
print("Shape:", df_industries.shape)

Shape: (422, 2)

In [7]:
df_industries.columns

Index(['industry_id', 'industry_name'], dtype='str')

In [8]:
print("Columns:", df_industries.columns.tolist())

Columns: ['industry_id', 'industry_name']

In [9]:
df_industries.info()

<class 'pandas.DataFrame'>
RangeIndex: 422 entries, 0 to 421
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   industry_id    422 non-null    int64
 1   industry_name  388 non-null    str
dtypes: int64(1), str(1)
memory usage: 6.7 KB

In [10]:
df_industries.dtypes

industry_id      int64
industry_name      str
dtype: object

> **Note:** In this course, the project data lives in a MySQL database. For local files, `pd.read_csv()` works the same way — the exploration steps (`head()`, `info()`, `dtypes`) are identical regardless of where the data came from.

---

---

## 🗄️ Loading the Project Data from MySQL <a class="anchor" id="gas"></a>

### 🧩 2. Connect to MySQL and load the postings table

For this course, the dataset is stored in a shared MySQL database. We use **SQLAlchemy** to create a connection engine and `pd.read_sql()` to run a query and load the result directly into a DataFrame.

### The connection string

SQLAlchemy needs five pieces of information to connect:

| Parameter | What it is | Example |
|---|---|---|
| `host` | Server address | `localhost` or an IP address |
| `port` | Port MySQL listens on | `3306` (MySQL default) |
| `user` | Database username | `student` |
| `password` | Database password | stored in `.env`, never in code |
| `database` | Name of the database | `linkedin` |

These are combined into a single **connection string**:

```
mysql+pymysql://user:password@host:port/database
```

### Why `.env`?

Credentials must never appear in a notebook or script that gets shared. The `.env` file stores them on your local machine — but only stays private if `.env` is listed in your `.gitignore`. Without that line, git will commit it like any other file.

> **For those going further:** `.env` is the right habit for learning and personal projects, but in production environments companies use a dedicated secrets manager (HashiCorp Vault, AWS Secrets Manager, Azure Key Vault) where credentials are fetched at runtime, access is audited, and secrets rotate automatically — no plaintext files on disk.


### Opening and closing

SQLAlchemy manages the connection automatically — you do not open or close it manually per query. When you are completely done with the database, call `engine.dispose()` to release all connections cleanly.

> **Connection pooling:** SQLAlchemy keeps a pool of open connections ready for reuse, which is more efficient than reconnecting for every query. The default settings are fine for this course — no configuration needed.

In [ ]:
!pip install

In [ ]:
import os
import pandas as pd
import numpy as np
import sqlalchemy as sa
from dotenv import load_dotenv

load_dotenv()  # reads credentials from the .env file into environment variables

DB_HOST = "3de0dac0-8513-4220-9ee7-414dc040c138.bn2a2uid0up8mv7mv2ig.databases.appdomain.cloud"
DB_PORT = "31131"
DB_NAME = "linkedin_jobs"
#DB_USER = '' # add here your username
#DB_PASSWORD = '' # add here your password

# Build the connection — each piece is named so you can see what it does
# Safe to print: url shows *** instead of your actual password
url = sa.engine.URL.create(
    drivername="mysql+pymysql",
    username=os.getenv("DB_USER", DB_USER),
    password=os.getenv("DB_PASSWORD", DB_PASSWORD),
    host=os.getenv("DB_HOST", DB_HOST),
    port=int(os.getenv("DB_PORT", DB_PORT)),
    database=os.getenv("DB_NAME", DB_NAME),
)

engine = sa.create_engine(url, connect_args={"ssl": {"check_hostname": False}})
print(url)  # password appears as ***

mysql+pymysql://admin:***@3de0dac0-8513-4220-9ee7-414dc040c138.bn2a2uid0up8mv7mv2ig.databases.appdomain.cloud:31131/linkedin_jobs

In [12]:
df_postings = pd.read_sql("SELECT * FROM postings LIMIT 100", engine)

In [13]:
df_postings.head()

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,2024-04-17 23:45:08,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,2024-04-11 17:51:27,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,2024-04-16 14:26:54,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,2024-04-12 04:23:32,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,2024-04-18 14:52:23,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0

### 🧪 Exercise 1 — Load the Companies Data

There is a second table: `companies_companies`. Load it into a variable called `df_companies` using `pd.read_sql()`.

In [ ]:
# Your code here

In [14]:
df_companies = pd.read_sql("SELECT * FROM companies_companies LIMIT 100", engine)

In [15]:
df_companies.head()

,company_id,name,description,company_size,state,country,city,zip_code,address,url
0,1009,IBM,"At IBM, we do more than work. We create. We cr...",7.0,NY,US,"Armonk, New York",10504,International Business Machines Corp.,https://www.linkedin.com/company/ibm
1,1016,GE HealthCare,Every day millions of people feel the impact o...,7.0,0,US,Chicago,0,-,https://www.linkedin.com/company/gehealthcare
2,1025,Hewlett Packard Enterprise,Official LinkedIn of Hewlett Packard Enterpris...,7.0,Texas,US,Houston,77389,1701 E Mossy Oaks Rd Spring,https://www.linkedin.com/company/hewlett-packa...
3,1028,Oracle,We’re a cloud technology company that provides...,7.0,Texas,US,Austin,78741,2300 Oracle Way,https://www.linkedin.com/company/oracle
4,1033,Accenture,Accenture is a leading global professional ser...,7.0,0,IE,Dublin 2,0,Grand Canal Harbour,https://www.linkedin.com/company/accenture

---

## 🔍 Inspecting the Data <a class="anchor" id="inspect"></a>

The first thing to do with any new dataset is get oriented — understand its shape, columns, and types.

### 🧩 3. Quick Look

| Function | Description |
|---|---|
| `df.head()` | First 5 rows |
| `df.tail()` | Last 5 rows |
| `df.shape` | (rows, columns) |
| `df.columns` | Column names |

In [16]:
df_postings.head()

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,2024-04-17 23:45:08,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,2024-04-11 17:51:27,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,2024-04-16 14:26:54,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,2024-04-12 04:23:32,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,2024-04-18 14:52:23,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0

In [ ]:
df_postings.tail()

In [17]:
print("Shape:", df_postings.shape)
print("Columns:", df_postings.columns.tolist())

Shape: (100, 31)
Columns: ['job_id', 'company_name', 'title', 'description', 'max_salary', 'pay_period', 'location', 'company_id', 'views', 'med_salary', 'min_salary', 'formatted_work_type', 'applies', 'original_listed_time', 'remote_allowed', 'job_posting_url', 'application_url', 'application_type', 'expiry', 'closed_time', 'formatted_experience_level', 'skills_desc', 'listed_time', 'posting_domain', 'sponsored', 'work_type', 'currency', 'compensation_type', 'normalized_salary', 'zip_code', 'fips']

### 🧩 4. Data Types and Non-Null Counts

| Function | Description |
|---|---|
| `df.dtypes` | Data type of each column |
| `df.info()` | Types + non-null count — good for spotting missing data |

In [18]:
df_postings.dtypes

job_id                                 int64
company_name                             str
title                                    str
description                              str
max_salary                           float64
pay_period                               str
location                                 str
company_id                           float64
views                                float64
med_salary                           float64
min_salary                           float64
formatted_work_type                      str
applies                              float64
original_listed_time          datetime64[us]
remote_allowed                       float64
job_posting_url                          str
application_url                          str
application_type                         str
expiry                        datetime64[us]
closed_time                           object
formatted_experience_level               str
skills_desc                              str
listed_time                   datetime64[us]
posting_domain                           str
sponsored                              int64
work_type                                str
currency                                 str
compensation_type                        str
normalized_salary                    float64
zip_code                             float64
fips                                 float64
dtype: object

In [19]:
df_postings.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 31 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   job_id                      100 non-null    int64
 1   company_name                77 non-null     str
 2   title                       100 non-null    str
 3   description                 100 non-null    str
 4   max_salary                  37 non-null     float64
 5   pay_period                  41 non-null     str
 6   location                    100 non-null    str
 7   company_id                  77 non-null     float64
 8   views                       96 non-null     float64
 9   med_salary                  4 non-null      float64
 10  min_salary                  37 non-null     float64
 11  formatted_work_type         100 non-null    str
 12  applies                     22 non-null     float64
 13  original_listed_time        100 non-null    datetime64[us]
 14  remote_allowed              13 non-null     float64
 15  job_posting_url             100 non-null    str
 16  application_url             19 non-null     str
 17  application_type            100 non-null    str
 18  expiry                      100 non-null    datetime64[us]
 19  closed_time                 0 non-null      object
 20  formatted_experience_level  3 non-null      str
 21  skills_desc                 10 non-null     str
 22  listed_time                 100 non-null    datetime64[us]
 23  posting_domain              10 non-null     str
 24  sponsored                   100 non-null    int64
 25  work_type                   100 non-null    str
 26  currency                    41 non-null     str
 27  compensation_type           41 non-null     str
 28  normalized_salary           41 non-null     float64
 29  zip_code                    82 non-null     float64
 30  fips                        79 non-null     float64
dtypes: datetime64[us](3), float64(10), int64(2), object(1), str(15)
memory usage: 24.3+ KB

> Notice that `listed_time` is stored as a datetime string. We will convert it to a timezone-aware datetime in the next section.

### 🧩 5. Summary Statistics

`df.describe()` gives a statistical summary of all numerical columns — count, mean, std, min, quartiles, max.

In [20]:
df_postings.describe()

,job_id,max_salary,company_id,views,med_salary,min_salary,applies,original_listed_time,remote_allowed,expiry,listed_time,sponsored,normalized_salary,zip_code,fips
count,1.000000e+02,37.000000,7.700000e+01,96.000000,4.000000,37.000000,22.000000,100,13.0,100,100,100.0,41.000000,82.000000,79.000000
mean,1.202171e+09,69503.524324,2.202201e+07,95.437500,113.602500,47584.032432,8.681818,2024-04-14 16:34:13.940000,1.0,2024-06-12 11:00:47.670000,2024-04-14 23:01:12.290000,0.0,78082.770732,54803.256098,26773.772152
min,9.217160e+05,19.000000,1.479800e+04,1.000000,23.000000,14.000000,1.000000,2024-03-23 03:55:20,1.0,2024-05-05 19:53:03,2024-04-05 19:53:03,0.0,4200.000000,1801.000000,1073.000000
25%,1.406633e+08,40.000000,9.885550e+05,2.000000,24.500000,25.000000,1.000000,2024-04-11 19:02:03,1.0,2024-05-12 06:43:00.500000,2024-04-11 19:47:08,0.0,53268.000000,31601.000000,12055.000000
50%,9.549925e+08,75000.000000,6.556800e+06,3.000000,40.705000,55000.000000,4.000000,2024-04-16 05:34:01,1.0,2024-05-18 15:59:43,2024-04-16 14:46:40,0.0,67500.000000,52812.500000,27053.000000
75%,2.147610e+09,110000.000000,2.863125e+07,7.000000,129.807500,75000.000000,6.750000,2024-04-18 20:03:48.500000,1.0,2024-05-19 13:55:02.250000,2024-04-18 20:12:51,0.0,100000.000000,80202.000000,40572.000000
max,2.974398e+09,300000.000000,9.921251e+07,8062.000000,350.000000,140000.000000,49.000000,2024-04-19 22:25:28,1.0,2024-10-16 19:05:01,2024-04-19 22:25:28,0.0,180000.000000,99501.000000,55089.000000
std,1.063710e+09,69076.991905,2.992619e+07,822.227831,158.339273,43328.587561,13.185079,NaN,0.0,NaN,NaN,0.0,37466.613782,29860.726158,16292.732035

### 🧪 Exercise 2 — Inspect the Companies Data

Using `df_companies`, answer the following:
1. How many rows and columns does it have?
2. What are the column names?
3. What data types are the columns?
4. What does `describe()` show?

In [21]:
# Your code here
df_companies.shape

(100, 10)

In [22]:
df_companies.columns

Index(['company_id', 'name', 'description', 'company_size', 'state', 'country',
       'city', 'zip_code', 'address', 'url'],
      dtype='str')

In [23]:
df_companies.dtypes

company_id        int64
name                str
description         str
company_size    float64
state               str
country             str
city                str
zip_code            str
address             str
url                 str
dtype: object

In [28]:
print(df_companies.dtypes)
df_companies.describe()

company_id        int64
name                str
description         str
company_size    float64
state               str
country             str
city                str
zip_code            str
address             str
url                 str
dtype: object

        company_id  company_size
count   100.000000    100.000000
mean   1310.250000      6.750000
std     169.640403      0.715979
min    1009.000000      3.000000
25%    1170.500000      7.000000
50%    1348.500000      7.000000
75%    1464.500000      7.000000
max    1586.000000      7.000000

---

## 🕐 Parsing Timestamps <a class="anchor" id="timestamps"></a>

### 🧩 6. Why Timestamps Matter

The `listed_time` column records when each posting was published — stored as a **datetime string** (e.g. `2024-04-17 23:45:08`). To work with it correctly in Pandas we parse it as a proper **datetime** type and attach a timezone.

`pd.to_datetime()` converts the string to a timezone-aware datetime. The `utc=True` argument localises the result to UTC.

In [29]:
df_postings['listed_time'].dtype

dtype('<M8[us]')

In [30]:
df_postings['listed_time'].iloc[0]

Timestamp('2024-04-17 23:45:08')

In [31]:
# Before
print("Before:", df_postings['listed_time'].dtype, "— value:", df_postings['listed_time'].iloc[0])

Before: datetime64[us] — value: 2024-04-17 23:45:08

In [32]:
# Convert to datetime and localise to UTC
df_postings['listed_time'] = pd.to_datetime(df_postings['listed_time'], utc=True)

In [33]:
# After
print("After: ", df_postings['listed_time'].dtype)
df_postings['listed_time'].head(3)

After:  datetime64[us, UTC]

0   2024-04-17 23:45:08+00:00
1   2024-04-11 17:51:27+00:00
2   2024-04-16 14:26:54+00:00
Name: listed_time, dtype: datetime64[us, UTC]

### 🧪 Exercise 3 — Check the Date Range

After parsing `listed_time`, find the earliest and latest posting dates. How wide is the date range? Does this change how you would approach time-based analysis?

In [ ]:
# Your code here

In [34]:
df_postings['listed_time'].min()

Timestamp('2024-04-05 19:53:03+0000', tz='UTC')

In [35]:
df_postings['listed_time'].max()

Timestamp('2024-04-19 22:25:28+0000', tz='UTC')

---

## 🏢 Loading a Second Table: Companies <a class="anchor" id="position"></a>

### 🧩 7. A Multi-Table Dataset

The LinkedIn dataset is spread across 11 related tables. The `postings` table is the main one — company information is stored separately in `companies_companies` to avoid repeating it for every posting.

| | Postings | Companies |
|---|---|---|
| Table | `postings` | `companies_companies` |
| Rows | ~40,059 | ~24,000 |
| Link | `company_id` | `company_id` |
| Contains | Job details, salary, location | Name, size, country, city |

The two tables are linked by `company_id`.

In [50]:
# Load the companies table
df_companies = pd.read_sql("SELECT * FROM companies_companies limit 100", engine)
df_companies.head()

,company_id,name,description,company_size,state,country,city,zip_code,address,url
0,1009,IBM,"At IBM, we do more than work. We create. We cr...",7.0,NY,US,"Armonk, New York",10504,International Business Machines Corp.,https://www.linkedin.com/company/ibm
1,1016,GE HealthCare,Every day millions of people feel the impact o...,7.0,0,US,Chicago,0,-,https://www.linkedin.com/company/gehealthcare
2,1025,Hewlett Packard Enterprise,Official LinkedIn of Hewlett Packard Enterpris...,7.0,Texas,US,Houston,77389,1701 E Mossy Oaks Rd Spring,https://www.linkedin.com/company/hewlett-packa...
3,1028,Oracle,We’re a cloud technology company that provides...,7.0,Texas,US,Austin,78741,2300 Oracle Way,https://www.linkedin.com/company/oracle
4,1033,Accenture,Accenture is a leading global professional ser...,7.0,0,IE,Dublin 2,0,Grand Canal Harbour,https://www.linkedin.com/company/accenture

In [38]:
print(df_companies.columns.tolist())

['company_id', 'name', 'description', 'company_size', 'state', 'country', 'city', 'zip_code', 'address', 'url']

---

## 🧹 Handling Missing Values <a class="anchor" id="nulls"></a>

### 🧩 8. Why Are There NaN Values?

Real-world datasets are rarely complete. In the LinkedIn postings, many columns are optional — companies are not required to disclose salary, remote status, or experience level.

| Operation | Code | Description |
|---|---|---|
| Count nulls | `df.isnull().sum()` | How many NaN per column |
| Percentage | `df.isnull().mean() * 100` | Null percentage |
| Drop rows | `df.dropna(subset=['col'])` | Remove rows where column is null |
| Fill NaN | `df.fillna(value)` | Replace NaN with a given value |

In [39]:
df_postings.isnull().sum()

job_id                          0
company_name                   23
title                           0
description                     0
max_salary                     63
pay_period                     59
location                        0
company_id                     23
views                           4
med_salary                     96
min_salary                     63
formatted_work_type             0
applies                        78
original_listed_time            0
remote_allowed                 87
job_posting_url                 0
application_url                81
application_type                0
expiry                          0
closed_time                   100
formatted_experience_level     97
skills_desc                    90
listed_time                     0
posting_domain                 90
sponsored                       0
work_type                       0
currency                       59
compensation_type              59
normalized_salary              59
zip_code                       18
fips                           21
dtype: int64

In [40]:
# As percentages — sorted highest first
(df_postings.isnull().mean() * 100).round(1).sort_values(ascending=False)

closed_time                   100.0
formatted_experience_level     97.0
med_salary                     96.0
posting_domain                 90.0
skills_desc                    90.0
remote_allowed                 87.0
application_url                81.0
applies                        78.0
min_salary                     63.0
max_salary                     63.0
compensation_type              59.0
normalized_salary              59.0
currency                       59.0
pay_period                     59.0
company_name                   23.0
company_id                     23.0
fips                           21.0
zip_code                       18.0
views                           4.0
title                           0.0
job_id                          0.0
description                     0.0
location                        0.0
original_listed_time            0.0
formatted_work_type             0.0
application_type                0.0
expiry                          0.0
listed_time                     0.0
job_posting_url                 0.0
work_type                       0.0
sponsored                       0.0
dtype: float64

In [41]:
df_postings.shape

(100, 31)

In [42]:
df_salary = df_postings.dropna(subset=['normalized_salary'])

In [43]:
df_salary.shape

(41, 31)

In [45]:
df_salary.head()

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,2024-04-17 23:45:08+00:00,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,2024-04-11 17:51:27+00:00,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,2024-04-16 14:26:54+00:00,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,2024-04-12 04:23:32+00:00,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,2024-04-18 14:52:23+00:00,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0

In [46]:
df_salary = df_postings.dropna(subset=['normalized_salary'])

pct_posts_with_salaries = len(df_salary)/len(df_postings) * 100

print(f"Postings with salary data: {len(df_salary):,} of {len(df_postings):,} ({pct_posts_with_salaries:.1f}%)")

Postings with salary data: 41 of 100 (41.0%)

### 🧪 Exercise 4 — Check Companies for Nulls

Check `df_companies` for missing values. Which columns have the most nulls? Focus on: `company_size`, `country`, `city`.

In [51]:
df_companies.shape

(100, 10)

In [52]:
df_companies.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   company_id    100 non-null    int64
 1   name          100 non-null    str
 2   description   100 non-null    str
 3   company_size  100 non-null    float64
 4   state         100 non-null    str
 5   country       100 non-null    str
 6   city          100 non-null    str
 7   zip_code      100 non-null    str
 8   address       100 non-null    str
 9   url           100 non-null    str
dtypes: float64(1), int64(1), str(8)
memory usage: 7.9 KB

In [48]:
# Your code here
df_companies.isnull().sum()

company_id      0
name            0
description     0
company_size    0
state           0
country         0
city            0
zip_code        0
address         0
url             0
dtype: int64

## ✅ Summary

| Concept | Key Point |
|---|---|
| `pd.read_csv()` | Loads a local CSV file into a DataFrame |
| `pd.read_sql()` | Runs a SQL query and loads the result into a DataFrame |
| `head()` / `tail()` / `shape` | Quick orientation: rows, columns, first/last rows |
| `dtypes` / `info()` | Column types and null counts |
| `describe()` | Statistical summary of numerical columns |
| `pd.to_datetime(utc=True)` | Parses a datetime string and localises to UTC |
| `isnull().sum()` | Count missing values per column |
| `dropna(subset=[...])` | Remove rows where a specific column is null |

[Go to top](#top)

### 🧠 Challenge

Instead of loading all columns from `postings`, write a SQL query that loads only: `job_id`, `title`, `formatted_experience_level`, `normalized_salary`, `location`, `views`.

1. Load this subset into `df_slim`
2. Compare the shape to the full `df_postings` — how many fewer columns?
3. In what situations would selecting specific columns matter for performance?

In [ ]:
# Your code here