# Session 4 | 3. Saving Results <a class="anchor" id="top"></a>

> Author: Patrícia Loureiro Rodrigues <plrodrigues@pbs.up.pt>
>
> Publication Date: April 2026

## Table of contents:
1. [Writing to CSV](#csv)
2. [Reading and Writing JSON](#json)
3. [Writing to a Database](#db)
4. [Exercises](#exercises)

---

At the end of this notebook, you will be able to:

- Write a computed DataFrame to a CSV file and read it back
- Build a JSON summary from aggregated results
- Write a DataFrame back to a MySQL database using `pd.to_sql()`
- Choose the right format for the job: CSV, JSON, or database table

---

## Why Saving Results Matters

In real analytics work, you will often need to:

- **Share results** with a colleague who does not use Python
- **Feed outputs** into another tool (dashboard, report, API)
- **Persist computed summaries** so you do not have to rerun expensive queries

> **Key rule:** save *computed results* (aggregations, summaries, model outputs) — not raw data that already lives in the database.

In [1]:
import os
import pandas as pd
import numpy as np
import sqlalchemy as sa
from dotenv import load_dotenv

load_dotenv() 

DB_HOST = "3de0dac0-8513-4220-9ee7-414dc040c138.bn2a2uid0up8mv7mv2ig.databases.appdomain.cloud"
DB_PORT = "31131"
DB_NAME = "linkedin_jobs"

url = sa.engine.URL.create(
    drivername="mysql+pymysql",
    username=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"),
    host=os.getenv("DB_HOST", DB_HOST),
    port=int(os.getenv("DB_PORT", DB_PORT)),
    database=os.getenv("DB_NAME", DB_NAME),
)

engine = sa.create_engine(url, connect_args={"ssl": {"check_hostname": False}})
print(url)  # password appears as ***

mysql+pymysql://admin:***@3de0dac0-8513-4220-9ee7-414dc040c138.bn2a2uid0up8mv7mv2ig.databases.appdomain.cloud:31131/linkedin_jobs

In [2]:
df_postings = pd.read_sql("SELECT * FROM postings", engine)
df_postings['listed_time'] = pd.to_datetime(df_postings['listed_time'], unit='ms', utc=True)
df_fulltime = df_postings[df_postings['formatted_work_type'] == 'Full-time'].copy()
df_salary = df_postings.dropna(subset=['normalized_salary']).copy()

In [3]:
# create a new folder
os.makedirs('../output', exist_ok=True)

---

## 💾 Writing to CSV <a class="anchor" id="csv"></a>

### 🧩 1. `df.to_csv()`

CSV is the simplest format to share tabular data. Use it for computed summaries — tables you have aggregated from the raw data.

```python
df.to_csv('path/to/file.csv', index=False)
```

In [4]:
# Compute a salary summary by experience level
exp_salary = (
    df_salary
    .groupby('formatted_experience_level')['normalized_salary']
    .agg(['count', 'median', 'mean'])
    .round(0)
    .reset_index()
)
exp_salary

  formatted_experience_level  count    median      mean
0                  Associate   1064   75000.0   83529.0
1                   Director    401  170000.0  170270.0
2                Entry level   2903   52500.0  368336.0
3                  Executive     98  208750.0  225763.0
4                 Internship    114   48953.0   61477.0
5           Mid-Senior level   3954  106984.0  184281.0

In [6]:
# Save the summary to CSV
exp_salary.to_csv('../output/salary_by_experience.csv', index=False, sep='|')
print('Saved.')

Saved.

**Useful parameters for `to_csv()`:**

| Parameter | Description | Example |
|---|---|---|
| `index=False` | Do not write the row index | almost always use this |
| `sep=';'` | Use semicolon instead of comma | for European locale tools |
| `encoding='utf-8'` | Character encoding | default, usually fine |

In [7]:
# Read it back to confirm the round-trip
df_check = pd.read_csv('../output/salary_by_experience.csv')
print('Rows:', len(df_check))
df_check

Rows: 6

   Unnamed: 0 formatted_experience_level  count    median      mean
0           0                  Associate   1064   75000.0   83529.0
1           1                   Director    401  170000.0  170270.0
2           2                Entry level   2903   52500.0  368336.0
3           3                  Executive     98  208750.0  225763.0
4           4                 Internship    114   48953.0   61477.0
5           5           Mid-Senior level   3954  106984.0  184281.0

---

## 🌐 Reading and Writing JSON <a class="anchor" id="json"></a>

### 🧩 2. When to Use JSON

JSON is better than CSV when:
- You need to share data with a web API or dashboard
- The structure is nested or has mixed types
- You want human-readable output with clear field names

### 🧩 3. Writing JSON with `df.to_json()`

In [8]:
# Compute a work type summary
work_summary = (
    df_postings
    .groupby('formatted_work_type')
    .agg(
        n_postings=('job_id', 'count'),
        avg_views=('views', 'mean')
    )
    .round(1)
    .reset_index()
)
work_summary

  formatted_work_type  n_postings  avg_views
0            Contract        3574       28.8
1           Full-time       32417       12.7
2          Internship         344       22.1
3               Other         115        8.6
4           Part-time        3034        7.7
5           Temporary         362       11.2
6           Volunteer         213        8.7

In [12]:
# Export to JSON — orient='records' gives a list of row objects
work_summary.to_json('../output/work_type_summary.json', orient='records', indent=2)
print('Saved.')

Saved.

In [13]:
# Inspect the raw file
import json

with open('../output/work_type_summary.json', 'r') as f:
    data = json.load(f)

print(json.dumps(data[0], indent=2))

{
  "formatted_work_type": "Contract",
  "n_postings": 3574,
  "avg_views": 28.8
}

### 🧩 4. Reading JSON back with `pd.read_json()`

In [14]:
df_work = pd.read_json('../output/work_type_summary.json', orient='records')
df_work

  formatted_work_type  n_postings  avg_views
0            Contract        3574       28.8
1           Full-time       32417       12.7
2          Internship         344       22.1
3               Other         115        8.6
4           Part-time        3034        7.7
5           Temporary         362       11.2
6           Volunteer         213        8.7

**Common `orient` options for `to_json()` / `read_json()`:**

| `orient` | Shape | Use |
|---|---|---|
| `'records'` | List of `{col: val}` dicts | APIs, most common |
| `'split'` | `{columns, index, data}` | Compact, preserves dtypes |
| `'index'` | `{index: {col: val}}` | When index is meaningful |

---

## 🗄️ Writing to a Database <a class="anchor" id="db"></a>

### 🧩 5. `df.to_sql()` — Persist Results Back to MySQL

You can write any DataFrame back to the database as a new table. This is useful when a computed summary needs to be shared with others who query the database directly.

```python
df.to_sql('table_name', con=engine, if_exists='replace', index=False)
```

| `if_exists` | Behaviour |
|---|---|
| `'fail'` | Raise an error if the table already exists |
| `'replace'` | Drop the table and recreate it |
| `'append'` | Add rows to the existing table |

In [15]:
exp_salary.head()

  formatted_experience_level  count    median      mean
0                  Associate   1064   75000.0   83529.0
1                   Director    401  170000.0  170270.0
2                Entry level   2903   52500.0  368336.0
3                  Executive     98  208750.0  225763.0
4                 Internship    114   48953.0   61477.0

In [16]:
# Write the salary summary back to the database
exp_salary.to_sql('salary_summary', con=engine, if_exists='replace', index=False)
print('Table written.')

Table written.

In [18]:
pd.read_sql("SHOW TABLES", engine)

           Tables_in_linkedin_jobs
0              companies_companies
1     companies_company_industries
2   companies_company_specialities
3        companies_employee_counts
4                    jobs_benefits
5              jobs_job_industries
6                  jobs_job_skills
7                    jobs_salaries
8              mappings_industries
9                  mappings_skills
10                        postings
11                  salary_summary
12               salary_summary_pr

In [17]:
# Read it back to confirm
pd.read_sql("SELECT * FROM salary_summary", engine)

  formatted_experience_level  count    median      mean
0                  Associate   1064   75000.0   83529.0
1                   Director    401  170000.0  170270.0
2                Entry level   2903   52500.0  368336.0
3                  Executive     98  208750.0  225763.0
4                 Internship    114   48953.0   61477.0
5           Mid-Senior level   3954  106984.0  184281.0

---

## 🧪 Exercises <a class="anchor" id="exercises"></a>

### 🧪 Exercise 1 — Save Top Locations

Compute the top 10 locations by number of full-time postings. Save the result as a CSV file in `../output/`.

In [ ]:
# Your code here

### 🧪 Exercise 2 — Export a Summary to JSON

Compute the number of postings and average `views` for each `formatted_experience_level`. Export the result as JSON with `orient='records'`. Read it back and confirm the result.

In [ ]:
# Your code here

### 🧪 Exercise 3 — Write to the Database

Compute the median salary by `location` for the top 10 locations (non-null salary only). Write the result to the database as a table called `location_salary_summary`. Read it back to confirm.

In [ ]:
# Your code here

---

## ✅ Summary

| Method | Code | Use |
|---|---|---|
| Write CSV | `df.to_csv('file.csv', index=False)` | Share tabular results |
| Read CSV | `pd.read_csv('file.csv')` | Load back a saved file |
| Write JSON | `df.to_json('file.json', orient='records', indent=2)` | APIs, dashboards |
| Read JSON | `pd.read_json('file.json', orient='records')` | Load back JSON |
| Write to DB | `df.to_sql('table', con=engine, if_exists='replace')` | Share via database |
| Read from DB | `pd.read_sql('SELECT * FROM table', engine)` | Confirm DB write |

[Go to top](#top)

### 🧠 Optional Challenge

Build a single summary DataFrame that combines:
- Number of postings per industry (requires joining with `job_industries` and `industries`)
- Median salary per industry (non-null only)
- Average views per industry

Save it as both a CSV and a database table. Which format would you choose to share with a colleague, and why?

In [ ]:
# Your code here
import pandas as pd
import numpy as np
import duckdb

np.random.seed(7)
n = 400

categories = np.random.choice(['Electronics', 'Clothing', 'Home', 'Sports'], n, p=[0.35, 0.25, 0.25, 0.15])
regions    = np.random.choice(['North', 'South', 'East', 'West'], n)
channels   = np.random.choice(['Online', 'In-store', 'Phone', None], n, p=[0.40, 0.35, 0.15, 0.10])
quantity   = np.random.randint(1, 8, n)
unit_price = np.where(
    np.random.rand(n) < 0.18, np.nan,
    np.random.choice([29.99, 49.99, 99.99, 149.99, 299.99, 499.99, 799.99], n)
)

df_sales = pd.DataFrame({
    'sale_id':    range(1, n + 1),
    'category':   categories,
    'region':     regions,
    'channel':    channels,
    'quantity':   quantity,
    'unit_price': unit_price,
})
df_sales['revenue'] = df_sales['quantity'] * df_sales['unit_price']

df_categories = pd.DataFrame({
    'category':   ['Electronics', 'Clothing', 'Home', 'Sports'],
    'department': ['Technology', 'Fashion', 'Living', 'Active Lifestyle'],
    'buyer':      ['Ana Silva', 'João Costa', 'Maria Pinto', 'Rui Ferreira'],
})